"""Headless browser acceptance against an isolated annotation workspace."""
import json
import threading
from functools import partial
from pathlib import Path
import tempfile
import time

from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains

import server as viewer
from studio import StudioLibrary, Handler, APP
from quality import DEFAULT_RULES


def main():
    evidence=APP/'workspace/evidence';evidence.mkdir(exist_ok=True,parents=True)
    profiles=evidence/'profiles';profiles.mkdir(exist_ok=True)
    before_reviews=StudioLibrary(APP/'workspace').store.all()
    with tempfile.TemporaryDirectory(prefix='ui-test-',dir=evidence) as tmp:
        lib=StudioLibrary(Path(tmp));(Path(tmp)/'cache').symlink_to(APP/'workspace/cache',target_is_directory=True)
        lib.add_root(APP.parent/'2026_09_10-17_40_44')
        lib.add_root(APP.parent/'mcap_viz.tar(1)/mcap_viz/mcap_0.mcap')
        ep=next(r for r in lib.refs.values() if r.episode_id=='episode_000131')
        viewer.STATIC_DIR=APP/'static'
        handler=partial(Handler,library=lib,robot=viewer.Robot(APP/'robot/g1_29dof_rev_1_0.urdf'))
        http=viewer.ThreadingHTTPServer(('127.0.0.1',0),handler)
        threading.Thread(target=http.serve_forever,daemon=True).start()
        url=f'http://127.0.0.1:{http.server_address[1]}'
        o=Options();o.add_argument('-headless')
        s=Service('/snap/bin/geckodriver',service_args=['--profile-root',str(profiles)],log_output=str(evidence/'geckodriver.log'))
        d=webdriver.Firefox(options=o,service=s);wait=WebDriverWait(d,70)
        def el(css):return d.find_element('css selector',css)
        def click(css):el(css).click()
        def fill(css,text):el(css).clear();el(css).send_keys(str(text))
        def check(name,ok):
            assert ok,name
            checks.append(name); print('PASS',name,flush=True)
        checks=[]
        try:
            d.set_window_size(1512,1100);d.get(url)
            wait.until(lambda _:len(d.find_elements('css selector','.episode-row'))==19)
            check('RoboCurate product name',d.title.startswith('RoboCurate'))
            check('dark workspace default',d.execute_script('return document.documentElement.dataset.theme')=='dark')
            click('#theme-toggle');check('light theme switch',d.execute_script('return document.documentElement.dataset.theme')=='light')
            click('#theme-toggle')
            d.execute_script("window.testErrors=[];window.addEventListener('error',e=>testErrors.push(e.message));window.addEventListener('unhandledrejection',e=>testErrors.push(String(e.reason)))")
            wait.until(lambda _:d.execute_script('return [...document.querySelectorAll(".thumb")].slice(0,4).every(i=>i.complete && i.naturalWidth>0)'))
            d.save_screenshot(str(evidence/'library.png'))
            check('catalog and thumbnails',len(d.find_elements('css selector','.episode-row'))==19)
            Select(el('#filter-outcome')).select_by_value('no')
            check('failure filter',len(d.find_elements('css selector','.episode-row'))==1)
            Select(el('#filter-outcome')).select_by_value('')
            fill('#search','episode_000131')
            check('search',len(d.find_elements('css selector','.episode-row'))==1)
            click('.select-ep');click('.ep-name')
            wait.until(lambda _:len(d.find_elements('css selector','[data-camera]'))==3)
            wait.until(lambda _:d.execute_script('return [...document.querySelectorAll("[data-camera]")].every(i=>i.complete && i.naturalWidth>0)'))
            wait.until(lambda _:len(d.find_elements('css selector','.event-list-row'))>0)
            click('#sidebar-toggle')
            check('collapsible sidebar preserves review layout',d.execute_script('return document.documentElement.dataset.sidebar==="collapsed" && document.documentElement.scrollWidth<=innerWidth'))
            d.save_screenshot(str(evidence/'focus-holocurate.png'))
            click('#sidebar-toggle')
            Select(el('#event-group')).select_by_value('right_arm');click('.event-list-row')
            check('event seeks to native peak',float(el('#timeline').get_attribute('value'))>0)
            old_event=el('.event-list-row.selected').get_attribute('data-event')
            if el('.review-options').get_attribute('open') is None:click('.review-options > summary')
            click('#fast-review')
            click('[data-decision="accepted"]')
            check('quick review advances',el('.event-list-row.selected').get_attribute('data-event')!=old_event)
            if el('.review-options').get_attribute('open') is None:click('.review-options > summary')
            click('#fast-review')
            check('event review draft',bool(d.find_elements('css selector','.event-list-row em.accepted')))
            click('[data-tool="batch-confirmed"]')
            check('batch preserves existing acceptance',len(d.find_elements('css selector','.event-list-row em.accepted'))==1)
            click('[data-tool="undo-batch"]')
            decisions=d.execute_script('return JSON.parse(localStorage.getItem(arguments[0])).event_decisions','rds-draft-'+ep.id)
            check('batch undo restores pending only',list(decisions.values())==['accepted'])
            first_time=el('.event-list-row').get_attribute('data-event')
            Select(el('#event-order')).select_by_value('priority')
            check('priority reorders issue list',el('.event-list-row').get_attribute('data-event')!=first_time)
            click('.event-list-row')
            resume_event=el('.event-list-row.selected').get_attribute('data-event')
            click('[data-tool="signal"]')
            wait.until(lambda _:len(d.find_elements('css selector','#signal-chart'))==1)
            check('event selects matching joint',el('#joint-select').get_attribute('value')=='26' or int(el('#joint-select').get_attribute('value'))>=22)
            Select(el('#signal-kind')).select_by_value('right_hand')
            check('hand signal has six motors',len(el('#joint-select').find_elements('tag name','option'))==6)
            click('button[data-stage-layout=balanced]')
            check('three cameras and telemetry',True)
            Select(el('#head-view')).select_by_value('crop-right')
            check('stereo eye switch','crop-right' in el('[data-cam-card="head"]').get_attribute('class'))
            Select(el('#head-view')).select_by_value('crop-left')
            click('[data-action="reset-playback"]')
            wait.until(lambda _:el('[data-camera="head"]').get_attribute('data-frame-index')=='0')
            index=lib.frame_store.public_index(ep.id)['cameras']['head']['times_s']
            click('[data-action="frame-next"]')
            wait.until(lambda _:el('[data-camera="head"]').get_attribute('data-frame-index')=='1')
            check('exact next frame',abs(float(el('#timeline').get_attribute('value'))-index[1])<1e-9)
            el('#timeline').send_keys(Keys.ARROW_RIGHT)
            wait.until(lambda _:el('[data-camera="head"]').get_attribute('data-frame-index')=='2')
            check('arrow keys step actual camera frames',abs(float(el('#timeline').get_attribute('value'))-index[2])<1e-9)
            el('#timeline').send_keys(Keys.HOME)
            wait.until(lambda _:el('[data-camera="head"]').get_attribute('data-frame-index')=='0')
            check('Home resets and pauses',el('#play-button').get_attribute('aria-pressed')=='false')
            d.execute_script('window.scrollTo(0,0)')
            before=int(el('[data-camera="head"]').get_attribute('data-paint-count') or 0)
            started=time.perf_counter();click('[data-action="play"]')
            wait.until(lambda _:time.perf_counter()-started>2.5)
            count=int(el('[data-camera="head"]').get_attribute('data-paint-count') or 0)-before
            measured=count/(time.perf_counter()-started)
            print('PLAYBACK',count,measured,d.execute_script('return {status:document.querySelector("#player-status").textContent,time:document.querySelector("#timeline").value,playing:document.querySelector("#play-button").getAttribute("aria-pressed") }'),flush=True)
            check('buffered playback advances image frames',count>15)
            (evidence/'playback-measurement.json').write_text(json.dumps(dict(loaded_frame_updates_per_second=round(measured,2),updates=count,seconds=round(time.perf_counter()-started,3),note='Headless Firefox, real episode_000131, prepared telemetry cache; image load updates, not a display-vsync benchmark.'),indent=2))
            ActionChains(d).move_to_element(el('#timeline')).click_and_hold().perform()
            check('scrubbing pauses playback',el('#play-button').get_attribute('aria-pressed')=='false')
            ActionChains(d).release().perform()
            check('scrub release restores prior playback',el('#play-button').get_attribute('aria-pressed')=='true')
            click('[data-action="play"]')
            check('synchronized playback',float(el('#timeline').get_attribute('value'))>0.5)
            click('[data-camera-expand="left_wrist"]')
            check('camera enlargement',el('.camera-grid').get_attribute('data-expanded')=='left_wrist')
            click('[data-camera-expand="left_wrist"]');Select(el('#primary-camera')).select_by_value('head')
            click('[data-action="chart-current"]')
            a=float(el('#chart-window').get_attribute('data-start'));b=float(el('#chart-window').get_attribute('data-end'))
            print('CHART_WINDOW',a,b,d.execute_script('return {toast:document.querySelector("#toast").textContent,html:document.querySelector("#chart-window").outerHTML,errors:window.testErrors}'),flush=True)
            check('local signal window',0<b-a<=2.00001)
            click('[data-action="chart-in"]')
            check('signal window zooms',float(el('#chart-window').get_attribute('data-end'))-float(el('#chart-window').get_attribute('data-start'))<b-a)
            click('[data-action="chart-reset"]')
            chart=el('#signal-chart');d.execute_script('arguments[0].scrollIntoView({block:"center"})',chart)
            width=chart.size['width']
            ActionChains(d).move_to_element_with_offset(chart,-int(width*.2),0).click_and_hold().move_by_offset(int(width*.4),0).release().perform()
            check('drag selects a signal time window',float(el('#chart-window').get_attribute('data-end'))-float(el('#chart-window').get_attribute('data-start'))<20)
            click('[data-action="chart-reset"]')
            d.save_screenshot(str(evidence/'review.png'))
            click('[data-detail="review"]');click('[data-grade="B"]');fill('#task-instruction','自动化界面验收，不代表真实任务审核')
            click('#clip-editor > summary')
            fill('#review-note','仅写入隔离测试数据库');click('.review-tags > summary');click('[data-tag="需裁剪"]')
            fill('#clip-label','验收片段');click('[data-action="add-clip"]')
            check('full duration default can be retained',len(d.find_elements('css selector','.clip-row'))==1)
            click('[data-edit-clip="0"]');fill('#clip-start','2');fill('#clip-end','3');click('[data-action="add-clip"]')
            check('clip created',len(d.find_elements('css selector','.clip-row'))==1)
            click('[data-action="save"]');wait.until(lambda _:'已保存' in el('#save-state').text)
            d.refresh();wait.until(lambda _:len(d.find_elements('css selector','#task-instruction'))==1)
            wait.until(lambda _:len(d.find_elements('css selector','.event-list-row.selected'))==1)
            check('review position restored',el('.event-list-row.selected').get_attribute('data-event')==resume_event)
            check('review persisted',el('#task-instruction').get_attribute('value')=='自动化界面验收，不代表真实任务审核')
            check('clip persisted',len(d.find_elements('css selector','.clip-row'))==1)
            check('event decision persisted',list(lib.store.all()[ep.id]['event_decisions'].values())==['accepted'])
            check('event evidence saved',lib.store.all()[ep.id]['event_evidence'][old_event]['event']['id']==old_event)
            click('[data-detail="review"]');fill('#review-note','第二次审核');click('[data-action="save"]');wait.until(lambda _:lib.store.all()[ep.id]['revision']==2)
            click('[data-action="history"]');wait.until(lambda _:el('#dialog').get_attribute('open') is not None)
            check('audit history','版本 1' in el('#dialog').text)
            history=lib.store.history(ep.id);seq=next(h['seq'] for h in history if h['after']['revision']==1)
            click(f'[data-restore-review="{seq}"]');wait.until(lambda _:lib.store.all()[ep.id]['revision']==3)
            wait.until(lambda _:d.execute_script('return document.querySelector("#review-note")?.value')=='仅写入隔离测试数据库')
            check('history restore creates a new revision',True)
            click('[data-action="show-quality"]');check('quality evidence',len(d.find_elements('css selector','.issue'))>0)
            click('.detail-more>summary');click('[data-detail="streams"]');check('stream table',len(d.find_elements('css selector','.technical-table tbody tr'))==19)
            wait.until(lambda _:d.execute_script('return document.querySelector("#robot-host")?.dataset.ready==="true"') or bool(d.find_elements('css selector','[data-action=robot-compat]')))
            if d.find_elements('css selector','[data-action=robot-compat]'):
                click('[data-action=robot-compat]');wait.until(lambda _:el('#robot-host').get_attribute('data-ready')=='true')
            # Software WebGL availability is an environmental property; capture it honestly.
            robot_ok=d.execute_script('return !!document.querySelector("#robot-host canvas")'); check('robot pose rendered',robot_ok)
            print('Robot renderer:',el('#robot-host canvas').get_attribute('data-renderer'),flush=True)
            d.save_screenshot(str(evidence/'robot.png'))
            click('a[href="#exports"]');wait.until(lambda _:len(d.find_elements('css selector','#export-list'))==1)
            click('[data-action="new-export"]');wait.until(lambda _:el('[data-action="confirm-export"]').is_enabled())
            check('export preflight visible','检查通过' in el('#preflight-result').text)
            click('[data-action="confirm-export"]')
            wait.until(lambda _:len(d.find_elements('css selector','a[download]'))==1)
            job=next(j for j in lib.exports() if j['state']=='done')
            check('browser export roundtrip',job['samples']==30 and job['valid_samples']>=27)
            d.save_screenshot(str(evidence/'exports.png'))
            click('a[href="#rules"]');wait.until(lambda _:len(d.find_elements('css selector','[data-rule]'))==len(DEFAULT_RULES))
            fill('[data-rule="tracking_p99_rad"]','0.6');click('[data-action="save-rules"]')
            wait.until(lambda _:lib.store.setting('rules',{})['tracking_p99_rad']==0.6)
            check('configurable rules',True)
            d.get(url+'/#review/'+ep.id);wait.until(lambda _:len(d.find_elements('css selector','#timeline'))==1)
            d.set_window_size(820,1100)
            check('responsive layout',d.execute_script('return document.documentElement.scrollWidth<=innerWidth'))
            d.save_screenshot(str(evidence/'review-compact.png'))
            # Reload resets the error recorder; initial interaction run has already asserted all actions.
            check('real annotations untouched',StudioLibrary(APP/'workspace').store.all()==before_reviews)
            (evidence/'ui-result.json').write_text(json.dumps(dict(passed=True,robot_rendered=robot_ok,isolated_workspace=True,checks=checks),indent=2))
        finally:
            d.quit();http.shutdown();http.server_close();lib.pool.shutdown();lib.export_pool.shutdown()


if __name__=='__main__':main()
